### ISSUE TITLE
CBC mode

### ISSUE THREAD

**Issue by chishiuanlu** [axiomatic-systems/skeyma#2]
Does skeyma support AES in CBC mode?
Thanks.

**Comment by barbibulle** [comment]
The interface and implementation stores key values regardless of which crypto algorithm or mode they will be used for. So you can use it to store AES keys that will be used in CTR, or CBC, or any other mode.

**Comment by chishiuanlu** [comment]
Awesome! Thanks for answering and the cool tool! Closing the question.
BTW, not sure if this has been brought up or not, I did have to modify package.json and changed "sqlite3": "2.2.x" to "sqlite3": "3.1.x" to get it work.

**Comment by barbibulle** [comment]
Thanks for the tip about upgrading the package reference to Sqlite 3.1.x,
we'll update the file.
